### ISSUE TITLE
JWKS URL not working?

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/bulk-data-server#10]
Trying authentication with a JWKS url: https://demo.careevolution.com/CNjwtcareevolutioncom.json fails with 401 `TypeError: Cannot read property 'keys' of undefined`

client ID: 

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJlZ2lzdHJhdGlvbi10b2tlbiJ9.eyJqd2tzX3VybCI6Imh0dHBzOi8vZGVtby5jYXJlZXZvbHV0aW9uLmNvbS9DTmp3dGNhcmVldm9sdXRpb25jb20uanNvbiIsImlzcyI6Imh0dHBzOi8vY2FyZWV2b2x1dGlvbi5jb20iLCJhY2Nlc3NUb2tlbnNFeHBpcmVJbiI6MTUsImlhdCI6MTUzNzE4NTY1OX0.670yVvoTgDMQd3TahrICfYYrVCLd-FQKo2PLQmUs_3Q
```

**Comment by vlad-ignatov** [comment]
To test this I will need your full JWKS (including the private key) if possible

**Comment by michelemottini** [comment]
I am using this certificate: https://fhir.careevolution.com/jwt.pfx - private key protected with password jwt.careevolution.com

**Comment by vlad-ignatov** [comment]
This is difficult to test and reproduce. For now I am stuck at "key_ops" missing in your public JWK. Can you add 
```
"key_ops": [
     "verify"
 ]
``` 
to your keys at  https://demo.careevolution.com/CNjwtcareevolutioncom.json? This is how the backend detects public keys (even though you are not supposed to host private keys).

**Comment by michelemottini** [comment]
Added `key_ops`. Getting the same error.

**Comment by vlad-ignatov** [comment]
But it works for me now. Can you share more details?

I am using a custom JS script to test, the core of which is:

```js
let jwtToken = {
    iss: client_id,
    sub: client_id,
    aud: token_url,
    exp: Date.now()/1000 + 300, // 5 min
    jti: crypto.randomBytes(32).toString("hex")
};

let signed = jwt.sign(jwtToken, privateKey, {
    algorithm: "RS384",
    keyid: "6662F2F81C1A45A7153DDB75C822B6673E6E7A29",
    header: {
        jku: jwks_url
    }
});

return lib.requestPromise({
    method: "POST",
    url   : token_url,
    json  : true,
    form  : {
        scope                : "system/*.*",
        grant_type           : "client_credentials",
        client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
        client_assertion     : signed
    }
})
```

**Comment by michelemottini** [comment]
Try without `header: { jku: jwks_url }` (that is optional)

**Comment by vlad-ignatov** [comment]
Aha! So that is where your error is coming from. I guess there is still some room for improvement of the spec around that because it is confusing.

It is labeled as "optional" because the server might not receive it. If the server receives a `jwks_url` header, then that is where it will load the keys from. Otherwise, it will use the keys provided at registration time. In other words, it is not strictly optional. It is more like you have to either provide it, or the server should be able to recognize you and have your keys...

In real-world implementations, a client would register with it's JWKS which will be stored somewhere and receive a `client_id`. Then at request time, the server can lookup those keys in its DB (unless `jwks_url` is set) and  authorize you.

On this server we do not store any data. Instead the JWKS is part of your `client_id` (which is also a token btw). By examining your `client_id` at https://jwt.io I can see that it does not contain `jwks` but only `jwks_url`. This means that you must provide the `jwks_url` header. Otherwise, the server is trying to read the `jwks` from your `client_id` token and throws that exception.

**Comment by michelemottini** [comment]
The specs at https://github.com/smart-on-fhir/fhir-bulk-data-docs/blob/master/authorization.md#server-obligations-for-signature-verification on how to verify signature clearly say the jku is not needed - and the jwks_url is contained in the client_id, so why can't the server use that?

**Comment by vlad-ignatov** [comment]
I think you are right about that. Currently, I am using the presence of `jku` header to switch between `jwks` and `jwks_url`. I was wondering  what `the registration-time JWKS URI (if any)` means if the `jku` is absent. Apparently, that would be the `jwks_url` from the client_id. I will fix that tomorrow.

**Comment by jmandel** [comment]
Glad to see the discussion landed here! and if there is anything we can do to clarify the specification, suggestions would be welcome on that front.

**Comment by michelemottini** [comment]
Thanks Vladimir

**Comment by michelemottini** [comment]
Works fine now, thanks!
