### ISSUE TITLE
Wrong authentication error responses

### ISSUE THREAD

**Issue by michelemottini** [smart-on-fhir/bulk-data-server#11]
The authentication error responses are 401 with a plain text body containing the error message, but according to the [OAuth2 specs](https://tools.ietf.org/html/rfc6749#section-5.2) they should be a 400 with a JSON body containing the error description

**Comment by vlad-ignatov** [comment]
This only applies to the auth part of the spec, correct?

I have converted all the errors thrown by the token and register endpoints to OAuth format with `error` and `error_description`. However, before committing them, I would like to post them here for comments. The reason is that I don't feel 100% confident that I have chosen the correct error names and response codes:

**token endpoint**

  - **400 invalid_grant** - with missing grant_type parameter
  - **400 unsupported_grant_type** - with invalid grant_type parameter
  - **400 invalid_request** - with missing client_assertion_type param
  - **400 invalid_request** - with invalid client_assertion_type param
  - **400 invalid_request** - with missing invalid_client_details_token param
  - **400 invalid_request** - with invalid invalid_client_details_token param
  - **400 invalid_request** - if the token does not contain valid client_id (sub) token
  - **400 invalid_grant** - if the id token contains {err:'token_expired_registration_token'} (simulated error)
  - **400 invalid_grant** - if the auth token 'aud' is wrong
  - **400 invalid_grant** - if the auth token 'iss' does not match the aud
  - **400 invalid_grant** - if the id token contains {err:'invalid_jti'} (simulated error)
  - **400 invalid_scope** - if the scope is invalid
  - **400 invalid_scope** - if the id token contains {err:'token_invalid_scope'} (simulated error)
  - **400 invalid_grant** - if the auth token jku is not whitelisted
  - **400 invalid_grant** - if local jwks has no keys
  - **400 invalid_grant** - if no jwks or jwks_url can be found
  - **400 invalid_grant** - if no public keys can be found
  - **400 invalid_grant** - if none of the public keys can decrypt the token
  - **401 invalid_client** - if the id token contains {err:'token_invalid_token'} (simulated error)

**registration endpoint**
  - **400 invalid_request** - if no 'Content-type: application/x-www-form-urlencoded' header is sent
  - **400 invalid_request** - with invalid 'dur' parameter
  - **400 invalid_request** - if both 'jwks' and 'jwks_url' are missing

Does that look correct to you?

**Comment by michelemottini** [comment]
They look good to me, thanks Vladimir (and yes, it applies only to the auth part)

**Comment by vlad-ignatov** [comment]
OK then. These updates are now deployed.

As for the testing, I don't think we can use the sample client for that.  However, I have hundreds of tests written already. If I have time, I was hoping to experiment during the connectathon and create a testing tool that people can launch against different servers...

**Comment by michelemottini** [comment]
Tested, works fine, thanks
